[project]
name = "07-jeremy"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "lxml>=6.0.1",
    "pandas>=2.2.3",
    "requests>=2.32.4",
]
